spring.application.name=LockTalk

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://root:HVRscWweiZZyNJallghXhWoPMxFNeWTa@centerbeam.proxy.rlwy.net:26546/railway
spring.datasource.username=root
spring.datasource.password=HVRscWweiZZyNJallghXhWoPMxFNeWTa


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
